update rspec version to 3.5
update rspec version to 3.5 to compensate for
"NoMethodError: undefined method `last_comment'" issue caused by an
incompatibility between rake and rspec.

For details on this issue, please refer to:
http://stackoverflow.com/questions/35893584/nomethoderror-undefined-method-last-comment-after-upgrading-to-rake-11